name: spellCheck

on: [pull_request,push,workflow_dispatch]

jobs:
  spell:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: spell_check
      uses: rojopolis/spellcheck-github-actions@v0

